services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      ITEN_FORGE_GOAL_TIME: "${ITEN_FORGE_GOAL_TIME:-2:50:00}"
      ITEN_FORGE_START_DATE: "${ITEN_FORGE_START_DATE:-2026-03-09}"
      ITEN_FORGE_UNIT: "${ITEN_FORGE_UNIT:-mi}"
